### ISSUE TITLE
Common stream will highlight common regulators/targets but not paths

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-graph-algos#10]
When you run a common stream query (both stream) with a length limit of 6 (from SyBLaRS), we get:
![common-stream](https://user-images.githubusercontent.com/3874988/173058599-7dd314ec-4fd7-4126-b795-2d345cd96db7.png)

The result looks fine but I don't see the paths from input nodes to the common regulators.

**Comment by ugurdogrusoz** [comment]
[TP53_regulates_trans.sbgn.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-graph-algos/files/8889226/TP53_regulates_trans.sbgn.txt)

**Comment by YusufZiyaOzgul** [comment]
Reason why this issue occurs is that SyBLaRS is not up-to-date when this query was applied. Now, SyBLaRS is up-to-date and there is no problem.
