### ISSUE TITLE
Clear previous results on new query

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-graph-algos#12]
When you apply a query, we highlight the results. Then a following query might return no result. In such cases, we keep displaying the results of the previous one, which is confusing. When applying a new query, we should always clear any highlights first.

**Comment by YusufZiyaOzgul** [comment]
Now, it works in way that it clears the highlights of result nodes and edges when apply button of the any query is pressed. Only the highlights of source nodes and target nodes( Paths From To query)  are not cleared. They remain until they are cleared by user(s). If user selects the nodes and press the add source nodes( or target nodes) button, these new nodes are added on existing nodes. There is no clear operation on existing nodes when new nodes are added. Highlights of source nodes are cleared only if clear button is pressed.
