### ISSUE TITLE
Demo improvements

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-graph-algos#2]
- [x] Let's use "Paths Between" instead of "Graph of Interest" in demo as well.
- [x] When "Apply Neighborhood Query" button is clicked without adding selected nodes, it throws error in the console.
- [x] Load the demo, select a node and add it via "Add Selected Nodes". Adjust direction to either bothstream or downstream, then click on "Apply Neighborhood Query" button. It doesn't find 1-neighborhood. If you do the same operation by adjusting direction to upstream, then it gives error in the console.
- [x] Let's move query selection drop-down to the right of "Select Query" label.
- [x] Add the three line explanation after "Clear" button (with a consistent empty space between them) and left align lines with the above buttons.
- [x] In each query selection, the menu that contains Limit, Direction etc. appears in different format. The vertical distances between options or the horizontal distances between option label and the selection box are different. Let's make the UI of these options uniform.

**Comment by YusufZiyaOzgul** [comment]
All issues solved now.You can check them.

**Comment by hasanbalci** [comment]
Added a new one.

**Comment by hasanbalci** [comment]
@YusufZiyaOzgul Graph enters inside the menu, let's also fix this!
![image](https://user-images.githubusercontent.com/22586369/170525327-79d87cac-76c6-493c-b35a-c7407a61c62c.png)

**Comment by hasanbalci** [comment]
It seems that the last problem still continues.
