### ISSUE TITLE
Add undirected version of Paths Between query

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-graph-algos#8]
As it's explained in the related paper, Paths Between query can be simplified for undirected search, so let's add that version as well. As a result, we'll have DIRECTED and UNDIRECTED versions of the Paths Between query like in Paths From To query.

**Comment by ugurdogrusoz** [comment]
We separated the issue about purifying / pruning incorrect paths. This simply addresses an undirected version for the query. Please check and close if OK.
